### ISSUE TITLE
Chapter 2 - Error: "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte"

### ISSUE THREAD

**Issue by owillner** [PracticalDL/Practical-Deep-Learning-Book#60]
When using the Non-Colab-Code in a Jupiter Notebook I receive the following error:

"2020-01-11 20:34:01.993022: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-11 20:34:02.030317: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fee2133a110 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-11 20:34:02.030342: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "visualization.py", line 165, in <module>
    process_image(image_path, output_prefix + "_output.jpg")
  File "visualization.py", line 128, in process_image
    class_index, class_name, prob_value = get_predictions(img, model)
  File "visualization.py", line 50, in get_predictions
    return decode_predictions_modified(preds, top=1)
  File "visualization.py", line 35, in decode_predictions_modified
    CLASS_INDEX = json.load(open(fpath))
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Users/olgawillner/venv2/bin/../lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte"

The Code for the Colab Workbook works completely fine. Does anyone have an idea why I receive the error "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte"?

**Comment by PracticalDL** [comment]
Have you downloaded the `imagenet_class_index.json` file, as per the instructions in the `README` file?

**Comment by meherkasam** [comment]
Have you downloaded the imagenet_class_index.json file, as per the instructions in the README file?

**Comment by meherkasam** [comment]
If you have, can you try changing line 35 to:

`CLASS_INDEX = json.load(open(fpath, encoding='utf-16'))`

**Comment by owillner** [comment]
Thanks!
